# Generated by Django 4.1.1 on 2022-09-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='BlogMedia', verbose_name='Thumbnail')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.CharField(max_length=500, verbose_name='Descrição')),
                ('text', models.TextField(verbose_name='Texto')),
            ],
        ),
    ]
