# Generated by Django 4.1.1 on 2022-09-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data da atualização')),
                ('title', models.CharField(max_length=500, verbose_name='Descrição da atualizaão')),
            ],
        ),
    ]
