# Generated by Django 4.1.1 on 2022-09-26 22:37

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_post_text_rendered_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=markdownfield.models.MarkdownField(),
        ),
    ]
