# Generated by Django 4.1.1 on 2022-09-26 22:39

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_rendered',
            field=markdownfield.models.RenderedMarkdownField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=markdownfield.models.MarkdownField(rendered_field='text_rendered'),
        ),
    ]
