# Generated by Django 4.1.1 on 2022-09-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_post_text_rendered_alter_post_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text_rendered',
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name='Texto'),
        ),
    ]
